pipeline {
    agent any
    stages {
        stage('Build Application') {
            steps {
                cmd_exec('mvn -f java-tomcat-sample/pom.xml clean package')
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
    }
    def cmd_exec(command) {
        return bat(returnStdout: true, script: "${command}").trim()
    }
}