pipeline {
    agent any
    stages {
        stage('Build Application') {
            steps {
                cmd_exec('mvn -f java-tomcat-sample/pom.xml clean package')
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
        stage('Deploy in staging Environment'){
            steps{
                build job : 'Deploy_Application_Staging_ENV'
            }
        }
        stage('Deploy in production Environment'){
            steps{
                timeout (time:5,unit:'DAYS'){
                    input message :'Approve Production Deployment?'
                }

                build job : 'Deploy_Application_Prod_ENV'
            }
        }
    }
    
}
def cmd_exec(command) {
        return bat(returnStdout: true, script: "${command}").trim()
    }